#!/bin/bash
# Setup script for YouTube→Telegram Summarizer Bot
#
# This script configures everything needed for the first run:
# - Installs Python dependencies
# - Prompts for API credentials
# - Creates .env configuration file
# - Sets up Telethon session (one-time phone verification)
# - Creates logs directory
# - Installs LaunchAgent for daily scheduling at 8am
#
# Usage: bash setup.sh

set -e  # Exit on any error

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGS_DIR="$HOME/logs"
LAUNCHAGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_NAME="com.youtube-telegram-summarizer.bot"
PLIST_PATH="$LAUNCHAGENTS_DIR/$PLIST_NAME.plist"

echo "=========================================="
echo "YouTube→Telegram Summarizer Bot Setup"
echo "=========================================="
echo ""

# Step 1: Check Python version
echo "Step 1: Checking Python installation..."
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 not found. Please install Python 3.9 or later."
    exit 1
fi

PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
echo "✓ Python $PYTHON_VERSION found"
echo ""

# Step 2: Install dependencies
echo "Step 2: Installing Python dependencies..."
DEPENDENCIES=(
    "yt-dlp"
    "requests"
    "python-telegram-bot"
    "telethon"
    "google-generativeai"
    "python-dotenv"
)

for dep in "${DEPENDENCIES[@]}"; do
    echo "  Installing $dep..."
    python3 -m pip install --quiet "$dep"
done
echo "✓ Dependencies installed"
echo ""

# Step 3: Create logs directory
echo "Step 3: Setting up logs directory..."
mkdir -p "$LOGS_DIR"
echo "✓ Logs directory: $LOGS_DIR"
echo ""

# Step 4: Prompt for API credentials
echo "Step 4: API Credentials Configuration"
echo "========================================"
echo ""

# YouTube: No credentials needed (RSS is public)
echo "✓ YouTube RSS: No credentials needed (public feeds)"

# Gemini API
echo ""
echo "Google Gemini API (for summarization):"
echo "  Get your free API key at: https://ai.google.dev/tutorials/setup"
read -p "  Enter GEMINI_API_KEY: " GEMINI_API_KEY
if [ -z "$GEMINI_API_KEY" ]; then
    echo "  ⚠ Skipping - you can add this later in .env"
    GEMINI_API_KEY=""
fi

# Telegram Bot Token
echo ""
echo "Telegram Bot Token:"
echo "  Create a bot via BotFather: https://t.me/botfather"
echo "  Keep the token secret!"
read -p "  Enter TELEGRAM_BOT_TOKEN: " TELEGRAM_BOT_TOKEN
if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    echo "  ❌ Bot token is required"
    exit 1
fi

# Telegram Chat ID
echo ""
echo "Telegram Group Chat ID:"
echo "  (Default: -1002007708028)"
read -p "  Enter TELEGRAM_CHAT_ID [use default]: " TELEGRAM_CHAT_ID
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:--1002007708028}"

# Telegram API credentials (for reading channel posts)
echo ""
echo "Telegram API Credentials (for reading channel posts):"
echo "  Get these at: https://my.telegram.org/apps"
read -p "  Enter TELEGRAM_API_ID: " TELEGRAM_API_ID
read -p "  Enter TELEGRAM_API_HASH: " TELEGRAM_API_HASH
read -p "  Enter phone number (format: +1234567890): " TELEGRAM_PHONE

echo ""

# Step 5: Create .env file
echo "Step 5: Creating .env configuration file..."
ENV_FILE="$PROJECT_DIR/.env"

cat > "$ENV_FILE" << EOF
# YouTube→Telegram Bot Configuration
# Generated by setup.sh - $(date)

# Gemini API (for summarization)
GEMINI_API_KEY=$GEMINI_API_KEY

# Telegram Bot API (for posting digests)
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID

# Telegram MTProto (for reading channel posts)
TELEGRAM_API_ID=$TELEGRAM_API_ID
TELEGRAM_API_HASH=$TELEGRAM_API_HASH
TELEGRAM_PHONE=$TELEGRAM_PHONE
TELETHON_SESSION_FILE=$PROJECT_DIR/telethon_session.session

# State management
STATE_FILE=$PROJECT_DIR/state.json

# Logging
DEBUG=false
EOF

chmod 600 "$ENV_FILE"  # Restrict permissions (contains secrets)
echo "✓ Created .env file (mode 600 for security)"
echo "  Location: $ENV_FILE"
echo ""

# Step 6: Test imports
echo "Step 6: Testing Python imports..."
python3 << 'PYTHON_TEST'
import sys
try:
    import yt_dlp
    import requests
    import google.generativeai
    import telethon
    print("  ✓ All Python dependencies imported successfully")
except ImportError as e:
    print(f"  ❌ Import error: {e}")
    sys.exit(1)
PYTHON_TEST
echo ""

# Step 7: Install LaunchAgent (macOS only)
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Step 7: Installing LaunchAgent for daily scheduling..."

    mkdir -p "$LAUNCHAGENTS_DIR"

    cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_NAME</string>
    <key>ProgramArguments</key>
    <array>
        <string>$HOME/.local/bin/python3</string>
        <string>-m</string>
        <string>youtube_telegram_bot.bot</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$PROJECT_DIR</string>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>8</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>$LOGS_DIR/youtube-telegram-bot.log</string>
    <key>StandardErrorPath</key>
    <string>$LOGS_DIR/youtube-telegram-bot-error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin</string>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
</dict>
</plist>
PLIST

    chmod 644 "$PLIST_PATH"
    echo "✓ Created LaunchAgent: $PLIST_PATH"
    echo "  Bot will run daily at 8:00 AM IST"

    # Unload old version if it exists, then load new one
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    launchctl load "$PLIST_PATH"
    echo "✓ LaunchAgent installed and loaded"

else
    echo "Step 7: Skipping LaunchAgent (macOS only)"
    echo "  On Linux/other OS, use cron instead:"
    echo "  0 8 * * * cd $PROJECT_DIR && python3 -m youtube_telegram_bot.bot"
fi

echo ""

# Step 8: Run initial test
echo "Step 8: Running initial test (dry-run)..."
cd "$PROJECT_DIR"
python3 << 'PYTHON_TEST'
import sys
sys.path.insert(0, ".")
from youtube_telegram_bot.bot import run_bot

print("  Running bot in dry-run mode...")
try:
    success = run_bot(dry_run=True)
    if success:
        print("  ✓ Bot test completed successfully")
    else:
        print("  ⚠ Bot test completed with warnings (check logs)")
except Exception as e:
    print(f"  ❌ Bot test failed: {e}")
    sys.exit(1)
PYTHON_TEST
echo ""

echo "=========================================="
echo "✓ Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Verify .env file: cat $ENV_FILE"
echo "2. Test manual run: python3 -m youtube_telegram_bot.bot"
echo "3. Check logs: tail -f $LOGS_DIR/youtube-telegram-bot.log"
echo ""
echo "Credentials stored in:"
echo "  - .env file (KEEP SECRET)"
echo "  - Telethon session: $PROJECT_DIR/telethon_session.session"
echo ""
echo "Daily digest will be sent at 8:00 AM"
echo ""
